//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgricultureApp.MauiClient.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AgricultureApp.MauiClient.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been added as a manager to farm {0}..
        /// </summary>
        public static string AddedAsFarmManager {
            get {
                return ResourceManager.GetString("AddedAsFarmManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivated fields.
        /// </summary>
        public static string CultFields {
            get {
                return ResourceManager.GetString("CultFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivated fields: {0}.
        /// </summary>
        public static string CultFieldsCount {
            get {
                return ResourceManager.GetString("CultFieldsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use email instead to login..
        /// </summary>
        public static string EmailLogin {
            get {
                return ResourceManager.GetString("EmailLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter two-factor code from authenticator application..
        /// </summary>
        public static string EnterTwoFactorCode {
            get {
                return ResourceManager.GetString("EnterTwoFactorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size: {0} {1}.
        /// </summary>
        public static string FieldSize {
            get {
                return ResourceManager.GetString("FieldSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string FieldStatus_Active {
            get {
                return ResourceManager.GetString("FieldStatus_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string FieldStatus_Inactive {
            get {
                return ResourceManager.GetString("FieldStatus_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under maintenance.
        /// </summary>
        public static string FieldStatus_UnderMaintenance {
            get {
                return ResourceManager.GetString("FieldStatus_UnderMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginPage {
            get {
                return ResourceManager.GetString("LoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed farms.
        /// </summary>
        public static string ManagedFarms {
            get {
                return ResourceManager.GetString("ManagedFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned: {0}.
        /// </summary>
        public static string ManagerAssignedAt {
            get {
                return ResourceManager.GetString("ManagerAssignedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers: {0}.
        /// </summary>
        public static string ManagerCount {
            get {
                return ResourceManager.GetString("ManagerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managers.
        /// </summary>
        public static string Managers {
            get {
                return ResourceManager.GetString("Managers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned farms.
        /// </summary>
        public static string OwnedFarms {
            get {
                return ResourceManager.GetString("OwnedFarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned fields.
        /// </summary>
        public static string OwnedFields {
            get {
                return ResourceManager.GetString("OwnedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned fields: {0}.
        /// </summary>
        public static string OwnedFieldsCount {
            get {
                return ResourceManager.GetString("OwnedFieldsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner&apos;s information.
        /// </summary>
        public static string OwnerInformation {
            get {
                return ResourceManager.GetString("OwnerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfilePage {
            get {
                return ResourceManager.GetString("ProfilePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been removed as farm manager from farm {0}..
        /// </summary>
        public static string RemovedAsFarmManager {
            get {
                return ResourceManager.GetString("RemovedAsFarmManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chalky.
        /// </summary>
        public static string SoilType_Chalky {
            get {
                return ResourceManager.GetString("SoilType_Chalky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clay.
        /// </summary>
        public static string SoilType_Clay {
            get {
                return ResourceManager.GetString("SoilType_Clay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        public static string SoilType_Generic {
            get {
                return ResourceManager.GetString("SoilType_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loamy.
        /// </summary>
        public static string SoilType_Loamy {
            get {
                return ResourceManager.GetString("SoilType_Loamy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string SoilType_Other {
            get {
                return ResourceManager.GetString("SoilType_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaty.
        /// </summary>
        public static string SoilType_Peaty {
            get {
                return ResourceManager.GetString("SoilType_Peaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandy.
        /// </summary>
        public static string SoilType_Sandy {
            get {
                return ResourceManager.GetString("SoilType_Sandy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silty.
        /// </summary>
        public static string SoilType_Silty {
            get {
                return ResourceManager.GetString("SoilType_Silty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication has been enabled..
        /// </summary>
        public static string TwoFactorEnabled {
            get {
                return ResourceManager.GetString("TwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use username instead to login..
        /// </summary>
        public static string UserNameLogin {
            get {
                return ResourceManager.GetString("UserNameLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        public static string VerifyButton {
            get {
                return ResourceManager.GetString("VerifyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor verification.
        /// </summary>
        public static string VerifyTwoFactorPage {
            get {
                return ResourceManager.GetString("VerifyTwoFactorPage", resourceCulture);
            }
        }
    }
}
